"""01_initial-db

Revision ID: 413924614894
Revises: 
Create Date: 2023-01-29 03:27:17.547094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413924614894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_url', sa.String(length=1000), nullable=False),
    sa.Column('short_url', sa.String(length=100), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_url'),
    sa.UniqueConstraint('short_url')
    )
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_date'), 'clicks', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_date'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_table('urls')
    # ### end Alembic commands ###
